name: aws-demo
vendor: aiken.qi@qq.com
icon: go.png
version: 1.0.1
summary: demo aws on snappy
description: This is a simple go webserver. It is a service

services:
  webserver:
    description: "aws demo"
    start: bin/golang-http
    caps:
     - network-client
     - network-service    
         
parts:
  webserver:
    plugin: go
    go-packages:
      - github.com/aiken/aws-demo

